apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: story
  labels:
    app: story
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      name: story
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: shortorg/story
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: story
---
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: story
spec:
  selector:
    app: story
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: production
  name: story
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  tls:
    - hosts:
        - story.short-d.com
      secretName: short-d.com-tls
  rules:
    - host: story.short-d.com
      http:
        paths:
          - backend:
              serviceName: story
              servicePort: 80
