#!/usr/bin/env bash

certbot certonly \
  --server https://acme-v02.api.letsencrypt.org/directory \
  --preferred-challenges dns \
  -d '*.short-d.com' \
  -d 'short-d.com' \
  --dns-digitalocean \
  --dns-digitalocean-credentials ~/.secrets/certbot/digitalocean.ini

declare -a namespaces=("testing" "staging" "production" "keel" "ingress" "db" "kube-system")

for namespace in "${namespaces[@]}"; do
    kubectl delete secret tls short-d.com-tls -n "$namespace"
    kubectl create secret tls short-d.com-tls \
      --key /etc/letsencrypt/live/short-d.com/privkey.pem \
      --cert /etc/letsencrypt/live/short-d.com/fullchain.pem -n "$namespace"
done