#!/usr/bin/env bash

kubectl create secret tls short-d.com-tls \
  --key /etc/letsencrypt/live/short-d.com/privkey.pem \
  --cert /etc/letsencrypt/live/short-d.com/fullchain.pem -n staging

kubectl create secret tls short-d.com-tls \
  --key /etc/letsencrypt/live/short-d.com/privkey.pem \
  --cert /etc/letsencrypt/live/short-d.com/fullchain.pem -n production